### ISSUE TITLE
Invalid Certificate on Minishift 

### ISSUE THREAD

**Issue by jfmatth** [clcollins/openshift-cronjob-example#2]
Hi, again thanks for this repo.

Running into a problem running the cronjob on a minishift instance due to a self-signed cert.

have u seen this before?

**Comment by clcollins** [comment]
I haven't - certs aren't really a part of the job framework at all, from what I can tell.  If you're getting cert problems with the job, but not on any other deployments, I would suspect it was the code.  Can you provide any context?

**Comment by jfmatth** [comment]
I'll try to replicate today, but honestly I got what I needed out of your
sample.  Thank you again.

J

**Comment by clcollins** [comment]
Sure thing, glad to help.
